language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - 7

sudo: true

install: travis_retry composer install --no-interaction --prefer-source

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-ldap

before_script:
  - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

after_script:
  - php vendor/bin/coveralls -v
